name: three_js_core
description: "Flutter three_js_core package converted from threejs and three_dart package made for three_js."
version: 0.0.2
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_core

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  flutter_angle:
    git:
      url: https://github.com/Knightro63/flutter_angle.git
  three_js_math:
    path: ../three_js_math

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

